### ISSUE TITLE
devp2p initial release progress tracker

### ISSUE THREAD

**Issue by q9f** [q9f/devp2p.cr#1]
ref https://ethereum.gitbooks.io/frontier-guide/devp2p.html

- [x] Secp256k1 https://github.com/q9f/secp256k1.cr
- [x] RLP https://github.com/q9f/rlp.cr
- [ ] Snappy compression
- [x] ethereum node identity (local persistent private key), see `Secp256k1::Ethereum::Enode.new`
- [ ] rlpx transport protocol
    ref https://github.com/ethereum/devp2p/blob/master/rlpx.md
    ref https://q9f.github.io/secp256k1.cr/Secp256k1/Ethereum/Enode.html
- [ ] ethereum node records (local database)
    ref https://github.com/ethereum/devp2p/blob/master/enr.md
- [ ] node discovery protocol v4
   ref https://github.com/ethereum/devp2p/blob/master/discv4.md

**Comment by q9f** [comment]
https://eips.ethereum.org/EIPS/eip-8

https://eips.ethereum.org/EIPS/eip-706
